imgur: remove separate sed calls for BSD and GNU
sed has -E extended regexp flag to be compatible with BSD:
http://stackoverflow.com/a/3139925

diff --git a/imgur b/imgur
--- a/imgur
+++ b/imgur
@@ -85,27 +85,14 @@ while [ $# -gt 0 ]; do
         continue
     elif [ "$(echo "$response" | grep -c "<error_msg>")" -gt 0 ]; then
         echo "Error message from imgur:" >&2
-        if [ "$(uname)" = "Linux" ]; then
-            # GNU (Linux) sed
-            echo "$response" | sed -r 's/.*<error_msg>(.*)<\/error_msg>.*/\1/' >&2
-        else
-            # BSD (OSX) sed
-            echo "$response" | sed -E 's/.*<error_msg>(.*)<\/error_msg>.*/\1/' >&2
-        fi
+        echo "$response" | sed -nE 's/.*<error_msg>(.*)<\/error_msg>.*/\1/p' >&2
         errors=true
         continue
     fi
 
     # parse the response and output our stuff
-    if [ "$(uname)" = "Linux" ]; then
-        # GNU (Linux) sed
-        url=$(echo "$response" | sed -r 's/.*<original_image>(.*)<\/original_image>.*/\1/')
-        deletehash=$(echo "$response" | sed -r 's/.*<deletehash>(.*)<\/deletehash>.*/\1/')
-    else
-        # BSD (OSX) sed
-        url=$(echo "$response" | sed -E 's/.*<original_image>(.*)<\/original_image>.*/\1/')
-        deletehash=$(echo "$response" | sed -E 's/.*<deletedash>(.*)<\/deletedash>.*/\1/')
-    fi
+    url=$(echo "$response" | sed -nE 's/.*<link>(.*)<\/link>.*/\1/p')
+    deletehash=$(echo "$response" | sed -nE 's/.*<deletehash>(.*)<\/deletehash>.*/\1/p')
     echo "$url"
     echo "Delete page: https://imgur.com/delete/$deletehash" >&2
 
